### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by gokulan97** [ShaastraWebops/spark-2018#1]
The **Spark** and **About Shaastra** tabs on the navigation bar point to the same thing. Remove **About Shaastra**.
Add a general Contact Us tab where u put region wise people to contact along with the mail id studentrelations@shaastra.org.
Instead of the background image in About Spark tab, request M&SR ppl to request the Design team for some image. Else Google it out and find something related to Spark or Shaastra.
Also, let the video be opaque, i.e when it pauses, it looks translucent.

**This issue will be closed once the site is completed**.

**Comment by avinashselvam** [comment]
Animations all look cool. Just make the site look clean.

Corrections:
- too many colours keep it to a maximum of 3
- too much text, literally too much and also put left-right padding
- I see 2 fonts. and the font used in navbar can be changed.
- look for a better background image
- the interaction with navbar is kinda off. The shadows mess up on hover
- Optimise for mobile as well
- Shaastra logo transition time is high and shadow is not good in my opinion. Also, change cursor

**Comment by gokulan97** [comment]
Status of the site?

**Comment by gokulan97** [comment]
There are a few things which needs to be done.
Add a collapsable navigation bar. In small screen, it doesnt look good.
Replace all the image backgrounds with plain colors.
Change the font
Remove the **A** symbol wherever it is present.
Remove the About Shaastra heading in the body(not from navbar!)
Reduce the circle size a bit so that all the states are visible on the same line(only in case of large screen).
Add some text in meta tag which would help in SEO. Eg. Shaastra 2018 IIT Madras Technical Festival, etc.

@avinashselvam add anything you want to this.
@Ronitron007 acknowledge this.

Also, FYI the site is currently running at [spark.shaastra.org](spark.shaastra.org).

**Comment by gokulan97** [comment]
And for the last tab "When and Where"
Can you keep the date to one side and elevate each circle, similar to the elevation of circles.

**Comment by gokulan97** [comment]
Also, if possible, link the Scroll and the navigation bar.

**Comment by gokulan97** [comment]
I have made a few UI changes to the site. Please do continue from that. @avinashselvam need you to look into it once.

**Comment by gokulan97** [comment]
What is the status of the site?

**Comment by gokulan97** [comment]
The site looks clean now. @avinashselvam  add your points too.

But the **When and Where** looks bit more spacious. My suggestion would be to have **When** in left and the Map in the right with the state names displaying on hovering over the state on the map.(of course in large screen only).

Also, the states Telangana and Karnataka have similar colors. It can be changed. @avinashselvam need your consent on this. Also, the background also looks similar to these two. So, even it could be changed.

**Comment by avinashselvam** [comment]
- Did you try a sans-serif font? serifs ain't looking good.
- Use black instead of grey for text in white bg.
- White color for Navbar text. try others but not grey, not clear.
- I notice a green in about spark animation, change it to something else. Or do away with the animation entirely.
- Compress the when and where section placing them side by side. split text and map into 2 halves. Don't have the gradient for the map.
- Remove the circle for July or use a different color.
- List the states rather than centre align.
- Remove shadow offset for structure cards. x - 0px y- 0px blur - 5px should do.
- Remove box for structure title and what is spark shadow to preserve consistency.
- if there is no particular reason for the current gradient you have chosen. try some dark and NOT 
  bright gradients.

Finally you dont have to follow these in an absolute fashion. Just look into them and maybe find a new solution. Else do as suggested. Contact me if you got queries.

**Comment by Ronitron007** [comment]
Currently there two issues in major I faced, needed your help with them..
Firstly, in the When and where section, putting animations using hover over the states itslef is giving problems cos even though the images are png, but the img elements are all rectangular and thus there areas overlap each other.
Secondly, I made the navbar collapsible but it collapses down when the window size is quite small... hence it really doesn't collapse in mobile window. I couldn't figure out why is it happening.

besides that, the Contact Us isn't there in the last commit, will put that very soon.

**Comment by gokulan97** [comment]
It wouldnt matter if it overlaps with other states too. Can you give a try and put screenshot?

**Comment by Ronitron007** [comment]
It gets very clumsy and multiple states get animated even if the cursor doesn't point to any state at all, I've tried using all sorts of display properties, noting seems to work well.

**Comment by gokulan97** [comment]
Go ahead with whatever you feel will look good.

**Comment by Ronitron007** [comment]
Changes applied in the last commit
I've done the hover thing as u asked,it is still very jittery so if it's not okay I can easily disable it.
please check the contact us tab added
I've taken care of the Color of states by adding grayscale to them
also changed the font color for the white background to grey
Removed the shadow offsets for the structure part, looks cleaner now
I added the box for all headings of tabs, thought it looked better and gave some uniformity throughout, will remove it if u don't like it
As of the gradient I also don't have great liking for it but i couldn't find any great dark color gradients that'd look good here, will surely update if I find any...

**Comment by gokulan97** [comment]
Ok ignore the animation on the states. Just have the colored images and the name on the states. 

And I would say to go with a single color rather than gradient for the background. Choose colors wisely from [here](https://material.io/guidelines/style/color.html). My suggestion would be #263238.

**Comment by gokulan97** [comment]
Status?

**Comment by Ronitron007** [comment]
Please Check this, It's a differnet theme, I'll push it to master branch if you think it's better 
https://ronitron007.github.io/Spark2018/

**Comment by gokulan97** [comment]
Put peace. @avinashselvam is doing it. But still what I feel would look good is reducing the height of navbar and fit each heading to the window. The blue could be a bit darker. Also there are lot of spaces which are not necessary.

**Comment by gokulan97** [comment]
Too much spaces. @avinashselvam can you remove them wherever necessary? and if possible link the scroll with the navigation bar.

**Comment by Ronitron007** [comment]
Please check this again, I've reduced all the colors and kept a single pallete.
https://ronitron007.github.io/Spark2018/

**Comment by gokulan97** [comment]
Nope, let @avinashselvam complete it. Meanwhile, the next task is ready :)

**Comment by gokulan97** [comment]
Closed.
